# Generated by Django 4.0.4 on 2022-08-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethanol',
            fields=[
                ('IdNo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Year', models.PositiveSmallIntegerField()),
                ('Month', models.CharField(max_length=10)),
                ('Product', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('REGION', models.CharField(blank=True, max_length=20, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=40, null=True)),
                ('EXPORTER', models.CharField(blank=True, max_length=200, null=True)),
                ('IMPORTER', models.CharField(blank=True, max_length=200, null=True)),
                ('QTYMT', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=25, null=True)),
                ('StorageType', models.CharField(blank=True, max_length=25, null=True)),
                ('MTonPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('VALUEUSD', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True)),
            ],
        ),
    ]
