# Generated by Django 4.0.4 on 2022-08-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandasdemo', '0003_alter_ethanol_qtymt_alter_ethanol_valueusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethanol',
            name='MTonPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ethanol',
            name='QTYMT',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ethanol',
            name='VALUEUSD',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
    ]
